### ISSUE TITLE
Create user model and save it to DB

### ISSUE THREAD

**Issue by ghost** [chingu-voyage7/Bears-Team-04#15]

**Comment by peoray** [comment]
What do you guys think would be accurate fields to add here?
Ex. 
- Full Name
- Username
- Password
- Email

I'd assume a user will also have a profile but that doesn't get added during sign up, but maybe will be like a user dashboard for a user to edit profile or something?

**Comment by ghost** [comment]
I think the full name isn't necessary for now. Just the bare minimum to get the user creation going is enough. We can always add more fields when we deem it necessary. It'll be a good idea to follow the same policy for the rest of the sprint.
