### ISSUE TITLE
Collaboration problem related to current repo issues

### ISSUE THREAD

**Issue by ghost** [chingu-voyage7/Bears-Team-04#19]
Hi guys. I observed something when we started being active in the repo.
It seems i divided the tasks too much, I see 2 problems right now:
- The issues are too simple, they're more like atomic commits than real tasks
- We won't be able to follow the git workflow like this: Currently the way it's divided, @jidemobell and @peoray will either have to create new branches or work on the same one, which is a bad option either way.

So here's what i'm proposing: The user stories will transform into backend/frontend tasks from now on, and will have a checklist for what has to be done. That way they'll be correctly scoped to allow us to work separately. As for the current tasks, since @jidemobell already started working on the registration backend, we'll delegate all the `type:backend` tasks related to registration to him.

Do you guys agree on this ?

**Comment by peoray** [comment]
I don't know, can a single person handle all the backend routes?
IMO, it doesn't really matter, like, for example, I need him to work on the mongoose setup before I can begin to work on mine, but doesn't matter, I'll wait, when he does it, I start mine, better, whoever has the time can still do anything as long as communication is maintained.

But after due discussion on the discord server, might be better to opt for your suggestions to avoid conflicts and other related issues
