### ISSUE TITLE
Add user creation functionality to the server

### ISSUE THREAD

**Issue by ghost** [chingu-voyage7/Bears-Team-04#21]
The following is only an attempt to keep track of related open issues. It doesn't represent all what needs to be done
- [x] Create `User` model. Closes #15  
- [x] Add `/register` route. Closes #16 

child to #5

**Comment by jidemobell** [comment]
![register_user.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a8c7a4cf9bb7f00138499d1/125516c66e82c728ace21e0d46fa919d2a9197ac9dd6aa50a14fb2d86b56357c2301a03f32dfa17dbd442e515c5b1aa810095b41fcf98b2ca0be3421de0e09ffcd7f1d2598694ef1e1c84afd13b0328a468fb7b98e48c3ef382def8f8a4b3f0c48.PNG)
