### ISSUE TITLE
Look into CI automation tools to include

### ISSUE THREAD

**Issue by ghost** [chingu-voyage7/Bears-Team-04#4]

**Comment by peoray** [comment]
I believe our options here are CircleCI and TravisCI, yeah?

**Comment by ghost** [comment]
We should discuss the viability of adding CI. Here's what I found from researching, and my opinion on each bullet:
- **It requires a change of workflow:** From the standard PR on dev after task completion, to frequent PRs into master (multiple ones daily in case of full time dev teams). It has good reasons for being adopted (avoiding monster-sized merges, to be able to quickly prevent and fix most of the bugs/issues related to code breakage for failed tests, or branch being behind). IMO, we should get comfortable with the current (basic) workflow before learning others that are more advanced. 
- **It requires the practice of testing:** Since CI runs unit/integration/functional tests . This is what made me doubt its viability: I fear adding testing frameworks *and* CI integration to our already long list of "learn while doing" is going to spread us thin, and prevent us from actually doing anything.

That's why as I see it, I'm with excluding CI from our workflow. Please either voice your approval or disapproval using reaction emojis, and/or comments.

**Comment by peoray** [comment]
I know a bit of testing and plan on incorporating it into our work but yes, I agree with you. We already have a long list to learn and this also will probably make us burn out. Maybe for future use

**Comment by ghost** [comment]
I also have a bit of experience with testing/CI although for self-contained desktop apps. And yeah in retrospective it seems like this will be too much for us to learn at the same time, especially since our project is far from self contained but includes a lot of interaction with externals (the user's browser, the database) which makes it more complicated. We'd need to look into mocking them out which I don't have any experience with so far.

**Comment by jidemobell** [comment]
you're right, it's not really necessary at this moment. we just simply need to come up with something that works, write good and thorough UTs/ITs and push to someplace like Heroku. I believe we can move on without CI a headache looking at out simple workflow.

would have been an added advantage for those looking for remote roles because this is always a requirement.
